### ISSUE TITLE
Todo Projet

### ISSUE THREAD

**Issue by Heartbroken-Git** [Pathf/Algo2Image#1]
- [x] Rédaction du Rapport
- [x] Compléter le fichier quadtree.cpp
- [x] Réalisation des tests dans testsUnitaires.cpp
- [x] Réalisation du programme de mesure dans Mesure.cpp
- [x] Réalisation des commentaires Doxygen

**Comment by Heartbroken-Git** [comment]
Projet terminé, je ferme l'issue.
